/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    NotificationDropdown: typeof import('./src/components/NotificationDropdown.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    Radio: typeof import('./src/components/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/components/Switch.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
